name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "SONIC ROM"
  comment: "MERISONICKEROMBHAI"
  url: "https://archive.org/download/microsoft_xbox360_s_part2/Sonic%20Unleashed%20%28USA%29%20%28En%2CJa%2CFr%2CDe%2CEs%2CIt%29.zip"
  file_name: "Sonic Unleashed (USA) (En,Ja,Fr,De,Es,It).zip"
  piece_size: 1 # Check the README.md for recommended piece size
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
